### ISSUE TITLE
Vibration while typing

### ISSUE THREAD

**Issue by EdHout** [ravimashru/obsidian-show-file-path#15]
Hi,

I find the plugin really useful. There's just one thing that really distracts me: because the width of different numeric characters is different, and the placement of the filepath is linked to the width of the word/character counter, the whole file path will slowly vibrate as one types. Is it possible to make it so the location of the file path is (mostly) fixed in the interface?

Thank you

**Comment by ravimashru** [comment]
Hey! 👋 

Thanks for using the plugin. I'm glad you find it useful. 🙂 

I spent some time looking at the issue and it looks like the problem is with how Obsidian is laying out the items in the status bar.

Unfortunately, I don't think there is a way to place community plugins to the right of core plugins (that would allow the file path to be shown on the right and the word count on the left; the word count would still vibrate but the file path would stay fixed)

**Comment by EdHout** [comment]
Hey, 

I see, that's a shame. I presume you can't fix the position of your plugin on the status bar (so with an absolute position) rather than trying to swap them around?

Thanks for taking a look!

**Comment by khbbkhbk** [comment]
try these CSS code:

```CSS
/* Show Current File Path修正*/
/* 修正其显示长路径时所导致的状态栏过长 */
.plugin-obsidian-show-file-path{
	display: inline-block;			/* 使text-overflow: ellipsis;生效 */
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;		/* 显示省略号来表示文本已被裁剪 */
	max-width: 9.5vw;
	margin-right:0px !important;
	font-weight: bold;
	padding-top: 5px;
}
.plugin-word-count{
	padding-left: 0px;
}
```
